spring.datasource.url=jdbc:mysql://database-1.ca1v19zl1v7m.us-east-1.rds.amazonaws.com:3306/Sucursal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=Vehiculosbd
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs
